src/YouFood/RestaurantBundle/Entity/User.php
<?php

namespace YouFood\RestaurantBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 *
 * @ORM\Table(name="yf_users")
 * @ORM\Entity(repositoryClass="YouFood\RestaurantBundle\Repository\UserRepository")
 */
class User implements UserInterface {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\ManyToMany(targetEntity="Group", inversedBy="users")
     *
     */
    private $groups;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToOne(targetEntity="Restaurant")
     * @ORM\JoinColumn(name="restaurant_id", referencedColumnName="id")
     */
    private $restaurant;

    public function __construct() {

        $this->isActive = true;
        $this->salt = md5(uniqid(null, true));
        $this->groups = new ArrayCollection();
    }

    public function __sleep() {
        return array('id');
    }

    public function getRolesAsArray() {

        $roles = new \Doctrine\Common\Collections\ArrayCollection();
        foreach ($this->groups as $group) {
            $roles->add($group->getRole());
        }
        return $roles;
    }

    /**
     * @inheritDoc
     */
    public function getUsername() {
        return $this->username;
    }

    /**
     * @inheritDoc
     */
    public function getSalt() {
        return $this->salt;
    }

    /**
     * @inheritDoc
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * @inheritDoc
     */
    public function getRoles() {

        return $this->groups->toArray();
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {
        
    }

    /**
     * @inheritDoc
     */
    public function equals(UserInterface $user) {
        return $this->username === $user->getUsername();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     */
    public function setUsername($username) {
        $this->username = $username;
    }

    /**
     * Set salt
     *
     * @param string $salt
     */
    public function setSalt($salt) {
        $this->salt = $salt;
    }

    /**
     * Set password
     *
     * @param string $password
     */
    public function setPassword($password) {
        $this->password = $password;
    }

    /**
     * Set email
     *
     * @param string $email
     */
    public function setEmail($email) {
        $this->email = $email;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     */
    public function setIsActive($isActive) {
        $this->isActive = $isActive;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive() {
        return $this->isActive;
    }

    /**
     * Add groups
     *
     * @param YouFood\RestaurantBundle\Entity\Group $groups
     */
    public function addGroup(\YouFood\RestaurantBundle\Entity\Group $groups) {
        $this->groups[] = $groups;
    }

    /**
     * Get groups
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getGroups() {
        return $this->groups;
    }

    /**
     * Set restaurant
     *
     * @param YouFood\RestaurantBundle\Entity\Restaurant $restaurant
     */
    public function setRestaurant(\YouFood\RestaurantBundle\Entity\Restaurant $restaurant) {
        $this->restaurant = $restaurant;
    }

    /**
     * Get restaurant
     *
     * @return YouFood\RestaurantBundle\Entity\Restaurant 
     */
    public function getRestaurant() {
        return $this->restaurant;
    }

}

src/YouFood/RestaurantBundle/Resources/views/Layout/main.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>{% block title %}YouFood{% endblock %}</title>

        <link href="{{ asset('bundles/bootstrap/css/bootstrap.css') }}" rel="stylesheet" type="text/css" />
        <style>
                #content{
                    margin-top: 50px;
                    padding: 30px;  
                }

                .majorTr{
                    background-color: #F9F9F9;
                }

                .titleTr{
                    background-color: #F5F5F5
                }
                
                .btn {
                    margin: 3px;
                }
               
            </style>

            <script src="{{ asset('js/jquery-1.7.2.js') }}" type="text/javascript"></script>
            <script src="{{ asset('bundles/bootstrap/js/bootstrap.js') }}" type="text/javascript"></script>



        </head>
        <body>

            <div id="sidebar">
            {% block sidebar %}
                    <div class="navbar navbar-fixed-top">
                        <div class="navbar-inner">
                            <div class="container">
                                <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </a>
                                <a href="{{ path('YouFoodRestaurantBundle_homepage') }}" class="brand">YouFood</a>
                                <div class="nav-collapse">
                                    
                                    {% if app.user.rolesAsArray is defined  %}

                                    <ul class="nav">
                                        
                                        {% if 'ROLE_SUPER_ADMIN' in app.user.rolesAsArray %}
                                            <li><a href="{{ path('Restaurant_list') }}">Restaurants</a></li>
                                            <li><a href="{{ path('Card_list') }}">Cards</a></li>
                                            <li><a href="{{ path('Plat_list') }}">Plats</a></li>
                                            <li><a href="{{ path('User_list') }}">Users</a></li>
                                        {% endif %}
                                            
                                    </ul>
                                    {% endif %}
                                    <div class="nav-collapse pull-right">
                                        <ul class="nav" id="loginHeader">
                                            {% if app.user.username is defined  %}
                                            <li style="margin-top: 10px;">Hello <b style="color: #0088CC;">{{ app.user.username }}</b> !</li>
                                            <li><a href="{{ path('login_out') }}">Logout</a></li>
                                            {% else %}
                                            <li><a href="{{ path('login') }}">Log in</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            {% endblock %}
                </div>

                <div id="content">
                        {% block body %}{% endblock %}
                    </div>
                </body>
            </html>

src/YouFood/RestaurantBundle/Resources/views/Layout/modal.html.twig
<div class="modal fade" id="{{ id }}Modal">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        {% block header %}
            <h3>Modal Title</h3>
        {% endblock %}
    </div>
    <div class="modal-body">
        {% block body %}{% endblock %}
    </div>
    <div class="modal-footer">
        {% block buttons %}
            <a href="#" class="btn" onclick="javascript: $('#{{ id }}Modal').modal('hide');">Close</a>
            <a class="btn btn-primary" onclick="javascript: $('#{{ id }}FormSubmit').click();">Add</a>
        {% endblock %}
    </div>
</div>

src/YouFood/RestaurantBundle/Resources/views/Layout/updateModal.html.twig
{% extends 'YouFoodRestaurantBundle:Layout:modal.html.twig' %}

{% block header %}
<h3>Update</h3>
{% endblock %}

{% block body %}

<script type="text/javascript">
(function() {

    {{id}}Manager = function() {

        return {

            initEvents : function() {
                $(".yf{{id}}").click(this.getModalContent);
            },

            getModalContent : function() {

                var path = $(this).attr('path');
                $('#yf{{id}}Content').html("Chargement...");

                $.ajax({
                        url: path,
                        success: function(html) {

                            $('#yf{{id}}Content').html(html);
                        },
                        error: function(){
                            $('#yf{{id}}Content').html('error.');
                        }
                    });      
            }
        }
    };

    }());

$(document).ready(function() {

    yf{{id}}Manager = {{id}}Manager();
    yf{{id}}Manager.initEvents();
        
});

    </script>

    <div id="yf{{id}}Content"></div>

{% endblock %}

{% block buttons %}
    <a href="#" class="btn" onclick="javascript: $('#{{id}}Modal').modal('hide');">Close</a>
    <a class="btn btn-primary" onclick="javascript: $('#{{ id }}FormSubmit').click();">Update</a>
{% endblock %}